version: '3.8'
services:
  dev-db:
    container_name: dev-db
    image: postgres:13
    ports:
      - ${DEV_DB_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - chat-backend
  test-db:
    container_name: test-db
    image: postgres:13
    ports:
      - ${TEST_DB_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - chat-backend
networks:
  chat-backend:
